version: '3.1'

services:

  postgres:
    container_name:  postgres
    image:  postgres:13
    restart: always
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: ./.env
