# Generated by Django 3.2.7 on 2021-11-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rememberme',
        ),
    ]
