# Generated by Django 3.2.7 on 2021-11-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='product_tag', to='product.Tag'),
        ),
    ]
