# Generated by Django 3.2.7 on 2021-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productversion_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Hex Code'),
        ),
    ]
