# Generated by Django 3.2.7 on 2021-11-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productversion_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='rating',
        ),
    ]
