# Generated by Django 3.2.7 on 2021-11-03 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_color_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, verbose_name='Hex Code'),
            preserve_default=False,
        ),
    ]
