# Generated by Django 3.2.7 on 2021-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productversion_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ex_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ex Price'),
        ),
    ]
