# Generated by Django 3.2.7 on 2021-10-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_image_productversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='productversion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='version_images', to='product.productversion', verbose_name='Product Version'),
        ),
    ]
