# Generated by Django 3.2.7 on 2021-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_color_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='ffffff', max_length=6, verbose_name='Hex Code'),
        ),
    ]
