
version: '3.1'

services: 
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: "always"
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx/vhost/:/etc/nginx/vhost.d:ro
            - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
            - ./nginx/proxy.conf/:/etc/nginx/proxy.conf
            - ./static/:/sellshop/static
            - ./media/:/sellshop/media

    postgres:
        image: postgres:9.6.6
        restart: always
        volumes:
            - ./postgredb:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file: ./.env

    redis:
      image: redis
      ports:
        - 6379:6379
      restart: always

    celery:
      build:
        context: .
        dockerfile: celery.dockerfile
      volumes:
        - .:/code
      command: celery -A nobi_project worker -l info
      links:
        - redis
        - postgres
      depends_on:
        - "redis"
        - "postgres"
      env_file: ./.env


    web:
        container_name: sellshop
        build: .
        restart: "always"
        ports:
            - "8000:8000"
        
        volumes:
            - .:/code/
            # - ./static/:/code/static
            # - ./media/:/code/media
        depends_on:
            - "postgres"
        env_file: ./.env

networks:
    default:
        external:
            name: nginx-proxy