# Generated by Django 3.2.7 on 2021-11-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Like'),
            preserve_default=False,
        ),
    ]
