# Generated by Django 3.2.7 on 2021-11-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is Main?'),
        ),
    ]
