# Generated by Django 3.2.7 on 2022-05-05 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20220505_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='typing_users',
            field=models.ManyToManyField(related_name='typing_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
