# Generated by Django 3.2.7 on 2022-05-06 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_blog_online_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='online_users',
            field=models.ManyToManyField(blank=True, related_name='online_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='typing_users',
            field=models.ManyToManyField(blank=True, related_name='typing_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
