# Generated by Django 3.2.7 on 2021-09-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='Wishlist_Product', to='product.ProductVersion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Wishlist', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='Cart_Product', to='product.ProductVersion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Cart', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Max 255 char.', max_length=255, verbose_name='Email Address')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('address', models.TextField(verbose_name='Address')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='User_Billing', to='account.user')),
            ],
        ),
    ]
