# Generated by Django 3.2.7 on 2021-11-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productversion_rating'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='company_name',
            field=models.CharField(blank=True, help_text='Max 255 char.', max_length=255, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Cart', to='product.productversion'),
        ),
    ]
