# Generated by Django 3.2.7 on 2021-11-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.shippingaddress', verbose_name='Shipping Address'),
        ),
    ]
