# Generated by Django 3.2.7 on 2021-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='Product_Cart', to='product.ProductVersion'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='Product_wishlist', to='product.ProductVersion'),
        ),
    ]
