# Generated by Django 3.2.7 on 2021-11-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
