# Generated by Django 3.2.7 on 2021-11-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_cart_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='company_name',
            field=models.CharField(blank=True, help_text='Max 255 char.', max_length=255, null=True, verbose_name='Company name'),
        ),
    ]
