# Generated by Django 3.2.7 on 2021-11-03 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_auto_20211102_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='country',
            field=django_countries.fields.CountryField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_Billing', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
